<<<<<<< HEAD

"use client";

import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
import { CartProvider } from "@/context/cart-context";
import { usePathname } from "next/navigation";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // hide Navbar & Footer only on auth routes
  const hideNavAndFooter =
    pathname === "/auth" || pathname === "/auth/forgetpassword";

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <div className="min-h-screen flex flex-col">
              {!hideNavAndFooter && <Navbar />}
              <main className="flex-1">{children}</main>
              {!hideNavAndFooter && <Footer />}
            </div>
          </CartProvider>
        </AuthProvider>
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> e5fdb6adbd7aeb3eabf5c05969815a9da451a9a3
      </body>
    </html>
  );
}
